[tool.poetry]
name = "pyrabbit"
version = "0.1.0"
description = ""
authors = ["Joacko <joaquinbf@live.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pygame = "1.9.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
